version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${DOCKER_PHP_CONTAINER_NAME}
    environment:
      - API_KEY=${API_KEY}
      - API_SECRET=${API_SECRET}
    volumes:
      - .:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - admin-panel-network

  db:
    image: mysql:8.0
    container_name: ${DOCKER_DB_CONTAINER_NAME}
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 3306:3306
    networks:
      - admin-panel-network

networks:
  admin-panel-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
